export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FETCH_USER = 'FETCH_USER';
export const CHANGE_STATUS = 'CHANGE_STATUS';
export const FETCH_BIRTHDAY_USERS = 'FETCH_BIRTHDAY_USERS';
export const FETCH_WORK_PLACE = 'FETCH_WORK_PLACE';
export const FETCH_WORK_PLACE_LIST_BY_FLOOR = 'FETCH_WORK_PLACE_LIST_BY_FLOOR';
export const RESERVE_WORK_PLACE = 'RESERVE_WORK_PLACE';
export const FETCH_PARKING = 'FETCH_PARKING';
export const FETCH_PARKING_LIST_BY_FLOOR = 'FETCH_PARKING_LIST_BY_FLOOR';
export const RESERVE_PARKING = 'RESERVE_PARKING';

